site_name: TMIP-EMAT + VisionEval
docs_dir: content
repo_url: http://github.com/tmip-emat/ve-integration
repo_name: tmip-emat/ve-integration
theme:
  name: material
  features:
    - content.code.annotate
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - admonition
  - pymdownx.details

plugins:
  - search
  - markdown-exec

nav:
- Home: 'index.md'
- scoping.md
- running.md
- example.md
